import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, ArrowRight, BrainCircuit, ShieldCheck, Sparkles } from "lucide-react";
import LiveSignals from "@/app/components/LiveSignals";
import { alternateLanguages } from "@/lib/i18n";
import styles from "./markets.module.css";

export const metadata: Metadata = {
  title: "Live AI Market Signals",
  description:
    "Explore public market intelligence generated by Exion AI across crypto and stocks, including confidence, expected ROI, risk, and risk-reward context.",
  alternates: { canonical: "/markets", languages: alternateLanguages("/markets") },
};

export default function MarketsPage() {
  return (
    <main className={styles.page}>
      <div className={styles.glowOne} />
      <div className={styles.glowTwo} />

      <nav className={styles.nav}>
        <Link className={styles.brand} href="/">
          <Image src="/krypnova-logo.jpeg" alt="Krypnova" width={42} height={42} priority />
          <span>KRYPNOVA</span>
        </Link>
        <Link className={styles.backLink} href="/">
          <ArrowLeft size={16} /> Back to Krypnova
        </Link>
      </nav>

      <section className={styles.hero}>
        <div className={styles.heroBadge}>
          <Sparkles size={15} /> Exion AI Market Intelligence
        </div>
        <h1>
          See the market through an
          <span> intelligent risk lens.</span>
        </h1>
        <p>
          Exion AI evaluates market structure, momentum, liquidity, transaction costs,
          portfolio context, and risk before classifying an opportunity. It can recommend
          LONG, SHORT, WATCH, or REJECT when conditions are not strong enough.
        </p>
        <div className={styles.heroActions}>
          <a href="#daily-ai-market-analysis" className={styles.primaryButton}>
            View Daily Analysis <ArrowRight size={17} />
          </a>
          <a href="#live-signals" className={styles.secondaryButton}>
            View Live Intelligence
          </a>
        </div>

        <div className={styles.trustBar}>
          <span><BrainCircuit size={18} /> Explainable assessments</span>
          <span><ShieldCheck size={18} /> Risk-first decision system</span>
          <span><Sparkles size={18} /> Multi-market monitoring</span>
        </div>
      </section>

      <div id="live-signals">
        <LiveSignals />
      </div>

      <section className={styles.privateLayer}>
        <div>
          <span className={styles.eyebrow}>Inside the platform</span>
          <h2>The public signal is only the first layer.</h2>
          <p>
            Krypnova members can review Exion AI&apos;s full reasoning, entry context, risk controls,
            position sizing, stop-loss logic, take-profit structure, portfolio fit, and execution plan.
          </p>
        </div>
        <Link href="https://app.krypnova.com" className={styles.primaryButton}>
          Unlock Full Intelligence <ArrowRight size={17} />
        </Link>
      </section>
    </main>
  );
}
