import type { Metadata } from "next";
import SeoLanding from "../components/SeoLanding";

const canonical = "https://www.krypnova.com/stock-analysis";
export const metadata: Metadata = { title: "AI Stock Analysis & Market Intelligence", description: "Analyze stocks with Krypnova and Exion AI using momentum, market regime, volatility, risk, confidence and portfolio context.", alternates: { canonical }, openGraph: { title: "AI Stock Analysis & Market Intelligence | Krypnova", description: "AI-powered stock market analysis with risk and portfolio context.", url: canonical, type: "website" } };
const faqs = [
  { question: "How can AI support stock analysis?", answer: "AI can help organize price behavior, momentum, volatility and market context into a structured assessment. Krypnova uses those signals to support clearer analysis, not to promise outcomes." },
  { question: "Is Krypnova a stock recommendation service?", answer: "Krypnova provides market intelligence and decision support. It does not provide personalized financial advice or guaranteed stock recommendations." },
  { question: "What stock-market factors does Krypnova evaluate?", answer: "The platform is designed to evaluate factors such as market regime, momentum, volatility, confidence, risk and portfolio exposure for supported equities." },
  { question: "Can Krypnova compare stocks and crypto?", answer: "Yes. Krypnova is designed as a multi-market intelligence platform, allowing users to analyze supported stocks and crypto using a consistent risk-aware framework." },
];
export default function Page(){const schema={"@context":"https://schema.org","@type":"FAQPage",mainEntity:faqs.map(f=>({"@type":"Question",name:f.question,acceptedAnswer:{"@type":"Answer",text:f.answer}}))};return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><SeoLanding eyebrow="Stock Market Intelligence" title="AI Stock Analysis for" highlight="Smarter Market Context" description="Krypnova uses Exion AI to organize stock-market momentum, regime, volatility, risk and confidence into clearer decision support." bullets={["Stock market regime","Momentum analysis","Portfolio exposure","Risk intelligence"]} sections={[{title:"See more than price movement",text:"A stock can rise while risk is also rising. Krypnova combines direction with market regime, volatility and confidence so the assessment has context."},{title:"Evaluate opportunity and downside together",text:"Krypnova is built around risk-aware analysis, helping users consider uncertainty, exposure and downside before acting on a market idea."},{title:"Portfolio-aware intelligence",text:"Individual stock analysis becomes more useful when connected to concentration and portfolio exposure. Krypnova is designed to bring those views together."},{title:"Consistent multi-market analysis",text:"Use the same intelligence framework across supported equities and digital assets instead of relying on disconnected tools for each market."}]} faqs={faqs}/></>}
