import type { Metadata } from "next";
import SeoLanding from "../components/SeoLanding";

const canonical = "https://www.krypnova.com/crypto-analysis";
export const metadata: Metadata = { title: "AI Crypto Analysis & Market Intelligence", description: "Analyze crypto markets with Krypnova and Exion AI using market structure, momentum, volatility, liquidity, risk and confidence context.", alternates: { canonical }, openGraph: { title: "AI Crypto Analysis & Market Intelligence | Krypnova", description: "AI-powered crypto market analysis with risk and confidence context.", url: canonical, type: "website" } };
const faqs = [
  { question: "How does AI help with crypto analysis?", answer: "AI can organize large amounts of market data, detect changing conditions and summarize risk factors. Krypnova uses Exion AI to turn those inputs into clearer market intelligence." },
  { question: "Does Krypnova guarantee profitable crypto trades?", answer: "No. Crypto trading involves significant risk and no system can guarantee profits. Krypnova is designed to support analysis and risk awareness." },
  { question: "What does Krypnova analyze in crypto markets?", answer: "Krypnova can evaluate market structure, momentum, liquidity, volatility, confidence, risk and broader market context for supported digital assets." },
  { question: "Can I use Krypnova for Bitcoin and Ethereum analysis?", answer: "Krypnova is designed to analyze supported crypto assets, including major markets, through a consistent market-intelligence framework." },
];
export default function Page(){const schema={"@context":"https://schema.org","@type":"FAQPage",mainEntity:faqs.map(f=>({"@type":"Question",name:f.question,acceptedAnswer:{"@type":"Answer",text:f.answer}}))};return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><SeoLanding eyebrow="Crypto Market Intelligence" title="AI Crypto Analysis for" highlight="Risk-Aware Trading" description="Use Exion AI to interpret crypto market conditions, momentum, volatility, liquidity and risk with a clearer framework for decision-making." bullets={["Crypto market regime","Volatility context","Risk scoring","Confidence analysis"]} sections={[{title:"Understand crypto market conditions",text:"Crypto markets can change quickly. Krypnova organizes market regime, trend strength and momentum so users can distinguish stronger setups from noisy conditions."},{title:"Analyze risk before opportunity",text:"Volatility and downside matter as much as upside. Krypnova makes risk context part of the analysis instead of treating it as an afterthought."},{title:"Explainable AI assessments",text:"Exion AI is designed to provide context around an assessment so users can understand why an opportunity is classified as strong, weak or worth watching."},{title:"One framework across digital assets",text:"Use a consistent approach to compare supported crypto assets rather than switching between disconnected indicators and dashboards."}]} faqs={faqs}/></>}
