import type { Metadata } from "next";
import SeoLanding from "../components/SeoLanding";

const canonical = "https://www.krypnova.com/market-analysis";
export const metadata: Metadata = { title: "AI Market Analysis for Crypto, Stocks & More", description: "Use Krypnova and Exion AI for multi-market analysis across crypto, stocks, forex and futures with risk, confidence, momentum and market-regime context.", alternates: { canonical }, openGraph: { title: "AI Market Analysis for Crypto, Stocks & More | Krypnova", description: "Multi-market AI analysis with risk, confidence and regime context.", url: canonical, type: "website" } };
const faqs = [
  { question: "What is AI market analysis?", answer: "AI market analysis applies machine learning and structured data processing to interpret market conditions, patterns and risk factors. Krypnova uses Exion AI to present that information as clearer decision support." },
  { question: "Which markets does Krypnova cover?", answer: "Krypnova is designed for crypto, stocks, forex and futures, with a shared framework for market conditions, opportunity strength and risk." },
  { question: "Why use one platform for multiple markets?", answer: "A unified platform can make it easier to compare opportunity, volatility and exposure across asset classes without switching between disconnected analysis systems." },
  { question: "Is AI market analysis financial advice?", answer: "No. Krypnova provides analytical information and decision support. Users remain responsible for their own trading and investment decisions." },
];
export default function Page(){const schema={"@context":"https://schema.org","@type":"FAQPage",mainEntity:faqs.map(f=>({"@type":"Question",name:f.question,acceptedAnswer:{"@type":"Answer",text:f.answer}}))};return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><SeoLanding eyebrow="Multi-Market Intelligence" title="AI Market Analysis Across" highlight="Crypto, Stocks, Forex & Futures" description="Krypnova brings multiple markets into one AI-powered intelligence layer so users can compare conditions, momentum, volatility, risk and opportunity with less noise." bullets={["Crypto analysis","Stock analysis","Forex intelligence","Futures context"]} sections={[{title:"One view across multiple markets",text:"Different asset classes behave differently, but users still need a consistent way to understand direction, confidence, volatility and risk. Krypnova provides that shared framework."},{title:"Detect changing market regimes",text:"Markets shift between trending, volatile and uncertain conditions. Exion AI is designed to recognize context so an opportunity is not judged in isolation."},{title:"Risk-aware opportunity discovery",text:"Krypnova combines opportunity strength with uncertainty and downside context, helping users avoid treating every signal as equally actionable."},{title:"From raw data to clear explanations",text:"The platform is designed to reduce information overload by converting complex inputs into concise market intelligence users can review before making a decision."}]} faqs={faqs}/></>}
